spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mobilelele_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
  sql:
      init:
          mode: never
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

