spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cooking_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  web:
    resources:
      static-locations: file:src/main/resources/static/
  mvc:
    hidden-method:
      filter:
        enabled: true
server:
  error:
    whitelabel:
      enabled: off
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

